
#spring.data.mongodb.database:
#  mygrocerylist

spring:
  data:
    mongodb:
#      authentication-database: mongoadmin
      uri: mongodb://mongoadmin:secret@localhost:27017/mydb?authSource=admin
      database: mydb
      port: 27017