services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
#        network_mode: host
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: mydb
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret